SiteChecker.WebApplication/Models/ErrorViewModel.cs
using System;

namespace SiteChecker.WebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SiteChecker.WebApplication/Controllers/HomeController.cs
namespace SiteChecker.WebApplication.Controllers
{
    using System.Diagnostics;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    using SiteChecker.WebApplication.Models;

    public class HomeController : Controller
    {
        private readonly SiteCheckerDbContext _context;

        public HomeController(SiteCheckerDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.UrlCheckTasks.ToListAsync());
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SiteChecker.WebApplication/Controllers/UrlCheckTasksController.cs
namespace SiteChecker.WebApplication.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    [Authorize]
    public class UrlCheckTasksController : Controller
    {
        private readonly SiteCheckerDbContext _context;

        public UrlCheckTasksController(SiteCheckerDbContext context)
        {
            _context = context;
        }

        // GET: UrlCheckTasks
        public async Task<IActionResult> Index()
        {
            return View(await _context.UrlCheckTasks.ToListAsync());
        }

        // GET: UrlCheckTasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var urlCheckTask = await _context.UrlCheckTasks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (urlCheckTask == null)
            {
                return NotFound();
            }

            return View(urlCheckTask);
        }

        // GET: UrlCheckTasks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UrlCheckTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Url,Login,Password")] UrlCheckTask urlCheckTask)
        {
            if (ModelState.IsValid)
            {
                _context.Add(urlCheckTask);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(urlCheckTask);
        }

        // GET: UrlCheckTasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var urlCheckTask = await _context.UrlCheckTasks.FindAsync(id);
            if (urlCheckTask == null)
            {
                return NotFound();
            }
            return View(urlCheckTask);
        }

        // POST: UrlCheckTasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Url,Login,Password")] UrlCheckTask urlCheckTask)
        {
            if (id != urlCheckTask.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(urlCheckTask);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UrlCheckTaskExists(urlCheckTask.Id))
                    {
                        return NotFound();
                    }

                    throw;
                }
                return RedirectToAction(nameof(Index));
            }

            return View(urlCheckTask);
        }

        // GET: UrlCheckTasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var urlCheckTask = await _context.UrlCheckTasks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (urlCheckTask == null)
            {
                return NotFound();
            }

            return View(urlCheckTask);
        }

        // POST: UrlCheckTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var urlCheckTask = await _context.UrlCheckTasks.FindAsync(id);
            _context.UrlCheckTasks.Remove(urlCheckTask);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UrlCheckTaskExists(int id)
        {
            return _context.UrlCheckTasks.Any(e => e.Id == id);
        }
    }
}

SiteChecker.WebApplication/Views/Home/Index.cshtml
@model IEnumerable<SiteChecker.UrlCheckTask>

@{
    ViewData["Title"] = "Мониторинг доступности сайтов";
}

<h2>Мониторинг доступности сайтов</h2>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.LastCheckDateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HttpStatusCode)
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Url)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastCheckDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HttpStatusCode)
            </td>
        </tr>
    }
    </tbody>
</table>

SiteChecker.WebApplication/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SiteChecker.WebApplication</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SiteChecker.WebApplication</a>*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Мониторинг</a></li>

                @if (SignInManager.IsSignedIn(User))
                {
                    <li><a asp-area="" asp-controller="UrlCheckTasks" asp-action="Index">Список сайтов</a></li>
                }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    @*<partial name="_CookieConsentPartial" />*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Мониторинг доступности сайтов</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

SiteChecker.WebApplication/Views/UrlCheckTasks/Create.cshtml
@model SiteChecker.UrlCheckTask

@{
    ViewData["Title"] = "Создание";
}

<h2>Создание новой задачи</h2>

<h4>Задача мониторинга доступности сайта</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Список</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SiteChecker.WebApplication/Views/UrlCheckTasks/Delete.cshtml
@model SiteChecker.UrlCheckTask

@{
    ViewData["Title"] = "Удаление";
}

<h2>Удаление</h2>

<h3>Удалить?</h3>
<div>
    <h4>Задача мониторинга доступности сайта</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Login)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Login)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastCheckResultJson)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastCheckResultJson)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastCheckDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastCheckDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HttpStatusCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HttpStatusCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-default" /> |
        <a asp-action="Index">Список</a>
    </form>
</div>

SiteChecker.WebApplication/Views/UrlCheckTasks/Details.cshtml
@model SiteChecker.UrlCheckTask

@{
    ViewData["Title"] = "Подробно";
}

<h2>Подробно</h2>

<div>
    <h4>Задача мониторинга доступности сайта</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Login)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Login)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastCheckResultJson)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastCheckResultJson)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastCheckDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastCheckDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HttpStatusCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HttpStatusCode)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Список</a>
</div>

SiteChecker.WebApplication/Views/UrlCheckTasks/Edit.cshtml
@model SiteChecker.UrlCheckTask

@{
    ViewData["Title"] = "Редактирование";
}

<h2>Редактирование</h2>

<h4>Задача мониторинга доступности сайта</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Список</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SiteChecker.WebApplication/Views/UrlCheckTasks/Index.cshtml
@model IEnumerable<SiteChecker.UrlCheckTask>

@{
    ViewData["Title"] = "Список задач";
}

<h2>Список</h2>

<p>
    <a asp-action="Create">Добавить</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Url)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Login)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastCheckDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HttpStatusCode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Url)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Login)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastCheckDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HttpStatusCode)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Просмотр</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>